DROP EXTERNAL TABLE IF EXISTS ext_do_datagen;
--CREATE EXTERNAL WEB TABLE ext_do_datagen ( result TEXT ) EXECUTE $$CHILD=$(($GP_SEGMENT_ID + 1));cd $GP_SEG_DATADIR/TPCDS/;$GP_SEG_DATADIR/TPCDS/dsdgen_do $SCALE $SEGCOUNT $CHILD$$ FORMAT 'TEXT';
CREATE EXTERNAL WEB TABLE ext_do_datagen ( result TEXT ) EXECUTE $$CHILD=$(($GP_SEGMENT_ID + 1));cd $GP_SEG_DATADIR/TPCDS/;$GP_SEG_DATADIR/TPCDS/dsdgen_do 1 $GP_SEGMENT_COUNT $CHILD$$ FORMAT 'TEXT';
